export default {
  'primary-1': 'rgb(var(--color-primary-1)/<alpha-value>)',
  'primary-2': 'rgb(var(--color-primary-2)/<alpha-value>)',
  'primary-3': 'rgb(var(--color-primary-3)/<alpha-value>)',
  'secondary-1': 'rgb(var(--color-secondary-1)/<alpha-value>)',
  'secondary-2': 'rgb(var(--color-secondary-2)/<alpha-value>)',
  'secondary-3': 'rgb(var(--color-secondary-3)/<alpha-value>)',
  'secondary-4': 'rgb(var(--color-secondary-4)/<alpha-value>)',
  'secondary-5': 'rgb(var(--color-secondary-5)/<alpha-value>)',
  'neutral-900': 'rgb(var(--color-neutral-900)/<alpha-value>)',
  'neutral-800': 'rgb(var(--color-neutral-800)/<alpha-value>)',
  'neutral-600': 'rgb(var(--color-neutral-600)/<alpha-value>)',
  'neutral-400': 'rgb(var(--color-neutral-400)/<alpha-value>)',
  'neutral-100': 'rgb(var(--color-neutral-100)/<alpha-value>)',
  'neutral-50': 'rgb(var(--color-neutral-50)/<alpha-value>)',
  'warning-500': 'rgb(var(--color-warning-500)/<alpha-value>)',
  'warning-300': 'rgb(var(--color-warning-300)/<alpha-value>)',
  'warning-50': 'rgb(var(--color-warning-50)/<alpha-value>)',
  'warning-700': 'rgb(var(--color-warning-700)/<alpha-value>)'
}
